version: '3'
services:
  libmonitordevcontainer:
    container_name: libmonitordevcontainer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=$USER
        - UID=$UID
    image: libmonitordevimage
    user: $UID
    volumes:
      - ..:/workspace/libmonitor
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    stdin_open: true
    working_dir: /workspace/libmonitor
    environment:
      - DISPLAY
      - MPLBACKEND=TKAgg
